#!/usr/bin/env python3
# K SO IT TURNS OUT THEREZ BASICALLY NOWAI 2 AKSHULLY
# MANIPULATE STRINGS IN LOLCODE WITHOUT TEH HAI 1.3
# SPECIFICASHUN, DIS AR TEH TEH BEST I CUD DO LMAO
#
# DIS JUS KATS TEH WERDZ 2 TEH LOLCODE DIS AR TEH
# TERRIBLE DO NOT AKSHULLY RUN DIS IT JUS 4 DA FUNNSIEZ
#
# DIS CUD ALSO BREAK UR SISTEM OR SOMETHIN SINCE
# ITZ RUNNIN EVRYTHIN THRU OS DOT SISTEM XD
import os as TEH_OPERATIN_SISTEM
import sys as TEH_OPERATIN_SISTEM_SISTEM

PATH_2_TEH_LOLCAT_LOLCODE_INTERPRETR = input("GIV PATH 2 TEH LOLCAT LOLCODE INTERPRETR PLZ KTHXBAI ")
if not TEH_OPERATIN_SISTEM.path.exists(PATH_2_TEH_LOLCAT_LOLCODE_INTERPRETR):
    TEH_OPERATIN_SISTEM_SISTEM.exit("TEH INTERPRETR CUD NOT BE FINDZ U SUX LULZ KTHXBAI")
if not TEH_OPERATIN_SISTEM.path.exists("./TEH_SPAM_PURRTECTOR.lol"):
    TEH_OPERATIN_SISTEM_SISTEM.exit("TEH SPAM PURRTECTOR CUD NOT BE FINDZ U SUX LULZ KTHXBAI")

with open("../invoices.txt", "r") as TEH_INVOICE_FILE:
    INVOICES = TEH_INVOICE_FILE.read()
for WORD in INVOICES.split(' '):
    with open("word.txt", "w") as WORDER:
        WORDER.write(WORD)
    TEH_OPERATIN_SISTEM.system(f"cat word.txt | {PATH_2_TEH_LOLCAT_LOLCODE_INTERPRETR} ./TEH_SPAM_PURRTECTOR.lol")
